title: HighTechManLand
default_lang: en
author:
  name: 'Ben Sewards'
  email: bensewards@outlook.com
taxonomies:
  - category
  - tag
  - month
  - author
metadata:
  description: 'HighTechManLand is home to innovative ideas on Sitecore CMS and Front End Technologies by Ben Sewards'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: ''
